# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/master_ip_system/master_ip_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system || ORIG_REF_NAME==master_ip_system} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_processing_system7_0_0/master_ip_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_processing_system7_0_0 || ORIG_REF_NAME==master_ip_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_Lab2_master_ip_0_0/master_ip_system_Lab2_master_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_Lab2_master_ip_0_0 || ORIG_REF_NAME==master_ip_system_Lab2_master_ip_0_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_auto_pc_0/master_ip_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_auto_pc_0 || ORIG_REF_NAME==master_ip_system_auto_pc_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_auto_us_0/master_ip_system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_auto_us_0 || ORIG_REF_NAME==master_ip_system_auto_us_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_axi_mem_intercon_0/master_ip_system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_axi_mem_intercon_0 || ORIG_REF_NAME==master_ip_system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_rst_ps7_0_100M_0/master_ip_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==master_ip_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_auto_pc_1/master_ip_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_auto_pc_1 || ORIG_REF_NAME==master_ip_system_auto_pc_1} -quiet] -quiet

# IP: bd/master_ip_system/ip/master_ip_system_ps7_0_axi_periph_0/master_ip_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==master_ip_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==master_ip_system_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: bd/master_ip_system/master_ip_system_ooc.xdc
