# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ryanh/Documents/Courses/1-2/SOPCDesignPracticeAndFPGASystemsDesign/labs/lab2/LED_constraint.xdc

# Block Designs: bd/Lab2_led/Lab2_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led || ORIG_REF_NAME==Lab2_led} -quiet] -quiet

# IP: bd/Lab2_led/ip/Lab2_led_processing_system7_0_0/Lab2_led_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led_processing_system7_0_0 || ORIG_REF_NAME==Lab2_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab2_led/ip/Lab2_led_Lab2_led_0_0/Lab2_led_Lab2_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led_Lab2_led_0_0 || ORIG_REF_NAME==Lab2_led_Lab2_led_0_0} -quiet] -quiet

# IP: bd/Lab2_led/ip/Lab2_led_ps7_0_axi_periph_0/Lab2_led_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab2_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab2_led/ip/Lab2_led_rst_ps7_0_100M_0/Lab2_led_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab2_led_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab2_led/ip/Lab2_led_auto_pc_0/Lab2_led_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_led_auto_pc_0 || ORIG_REF_NAME==Lab2_led_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab2_led/Lab2_led_ooc.xdc
