# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab1_SDK_sys/Lab1_SDK_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_SDK_sys || ORIG_REF_NAME==Lab1_SDK_sys} -quiet] -quiet

# IP: bd/Lab1_SDK_sys/ip/Lab1_SDK_sys_processing_system7_0_0/Lab1_SDK_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_SDK_sys_processing_system7_0_0 || ORIG_REF_NAME==Lab1_SDK_sys_processing_system7_0_0} -quiet] -quiet

# XDC: bd/Lab1_SDK_sys/Lab1_SDK_sys_ooc.xdc
