/*
 * vmm.cpp - Userspace test application for HW5 VMM AXI-Lite IP
 *
 * Ported from SDK helloworld.c (hw4).
 * Communicates with the vmm kernel driver via ioctl on /dev/vmm-master.
 *
 * ioctl cmd convention:
 *   Writes: ioctl(fd, CMD_INDEX + 64*1024, value)
 *   Reads:  ioctl(fd, CMD_INDEX, 0)
 *
 *   cmd 0  -> REG_CTRL  write (start)
 *   cmd 1  -> REG_DIM   write
 *   cmd 2  -> REG_I_ADDR write
 *   cmd 3  -> REG_I_DAT_L write
 *   cmd 4  -> REG_I_DAT_H write (triggers HW SRAM write)
 *   cmd 5  -> REG_O_ADDR write
 *   cmd 6  -> REG_O_DAT  read
 *   cmd 7  -> REG_CTRL   read (poll finish bit)
 *
 * Usage (on Zedboard after insmod vmm.ko):
 *   ./vmm
 */

#include <iostream>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>

/* ioctl cmd indices — must match vmm.c driver definitions */
#define CMD_CTRL_WR    0
#define CMD_DIM_WR     1
#define CMD_I_ADDR_WR  2
#define CMD_I_DAT_L_WR 3
#define CMD_I_DAT_H_WR 4
#define CMD_O_ADDR_WR  5
#define CMD_O_DAT_RD   6
#define CMD_CTRL_RD    7

/* convenience macros matching the SDK Xil_Out32 / Xil_In32 style */
#define VMM_WRITE(fd, cmd, val) ioctl((fd), (cmd) + 64*1024, (val))
#define VMM_READ(fd, cmd)       ioctl((fd), (cmd), 0)

int main() {
    std::cout << "\n--- VMM Hardware Accelerator Verification ---\n\n";

    /* --------------------------------------------------------
     * Step 0: Open the driver device node
     * -------------------------------------------------------- */
    int fd = open("/dev/vmm-master", O_RDWR);
    if (fd < 0) {
        std::cout << "Cannot open /dev/vmm-master\n";
        std::cout << "Did you run: insmod vmm.ko ?\n";
        return -1;
    }

    /* ========================================================
     * Input data generated by Python gen_rand.py
     * Replace these arrays with your own generated values.
     * ======================================================== */
    unsigned int input_data_high[] = {0xb3870423, 0x52b64f09, 0xd98038fc, 0xaf00937b};
    unsigned int input_data_low[]  = {0x9fa6fff0, 0x4c10768b, 0x0286ae40, 0xc75b0266};
    int golden_data[]              = {3, 98, -9};
    /* ======================================================== */

    /* --------------------------------------------------------
     * Step 1: Auto-derive M and N dimensions
     * Same formula as SDK app:
     *   total_depth = M/16 + (M/16)*N
     *   => M = (total_depth * 16) / (1 + N)
     * -------------------------------------------------------- */
    int n_val = sizeof(golden_data) / sizeof(golden_data[0]);
    int total_input_depth = sizeof(input_data_high) / sizeof(input_data_high[0]);
    int m_val = (total_input_depth * 16) / (1 + n_val);

    std::cout << "Detected Dimensions : M = " << m_val
              << ", N = " << n_val << "\n";
    std::cout << "Total SRAM Lines    : " << total_input_depth << "\n\n";

    /* --------------------------------------------------------
     * Step 2: Write M and N into hardware dimension register
     * Upper byte = M, lower byte = N
     * -------------------------------------------------------- */
    unsigned int dim_config = (m_val << 8) | n_val;
    VMM_WRITE(fd, CMD_DIM_WR, dim_config);

    /* --------------------------------------------------------
     * Step 3: Write input data into hardware Input SRAM
     * Each entry: write address, then low word, then high word.
     * Writing high word triggers the hardware 64-bit SRAM write.
     * -------------------------------------------------------- */
    std::cout << "Writing test data to Input SRAM...\n";
    for (int i = 0; i < total_input_depth; i++) {
        VMM_WRITE(fd, CMD_I_ADDR_WR,  i);
        VMM_WRITE(fd, CMD_I_DAT_L_WR, input_data_low[i]);
        VMM_WRITE(fd, CMD_I_DAT_H_WR, input_data_high[i]);
    }

    /* --------------------------------------------------------
     * Step 4: Send 1-cycle start pulse
     * Assert bit[0] high then immediately low.
     * The driver's edge detector converts this into a
     * single-cycle start_pulse for the VMM state machine.
     * -------------------------------------------------------- */
    std::cout << "Sending Start Pulse to Hardware...\n";
    VMM_WRITE(fd, CMD_CTRL_WR, 0x01);  /* assert start */
    VMM_WRITE(fd, CMD_CTRL_WR, 0x00);  /* deassert    */

    /* --------------------------------------------------------
     * Step 5: Poll finish bit (REG_CTRL bit[1])
     * -------------------------------------------------------- */
    std::cout << "Waiting for hardware to compute...\n";
    long status;
    do {
        status = VMM_READ(fd, CMD_CTRL_RD);
    } while (!(status & 0x02));

    /* clear control register for next run */
    VMM_WRITE(fd, CMD_CTRL_WR, 0x00);
    std::cout << "Hardware Finished!\n\n";

    /* --------------------------------------------------------
     * Step 6: Read results and verify against golden data
     * -------------------------------------------------------- */
    std::cout << "Verifying Results:\n";
    int passed = 1;

    for (int j = 0; j < n_val; j++) {
        VMM_WRITE(fd, CMD_O_ADDR_WR, j);
        long result = VMM_READ(fd, CMD_O_DAT_RD);

        /* sign-extend 12-bit result to 32-bit signed int
         * bit[11] is the sign bit; if set, fill upper 20 bits with 1s */
        int signed_res = (int)(result & 0xFFF);
        if (signed_res & 0x800)
            signed_res |= 0xFFFFF000;

        std::cout << "  Result [" << j << "]: " << signed_res
                  << "\t| Golden: " << golden_data[j];

        if (signed_res != golden_data[j]) {
            std::cout << "  <-- [MISMATCH]\n";
            passed = 0;
        } else {
            std::cout << "  <-- [CORRECT]\n";
        }
    }

    /* --------------------------------------------------------
     * Step 7: Final verdict
     * -------------------------------------------------------- */
    std::cout << "\n";
    if (passed) {
        std::cout << "\n\n";
        std::cout << "        ==================================\n";
        std::cout << "        ==   ALL TESTS PASSED! MEOW~    ==\n";
        std::cout << "        ==================================\n";
        std::cout << "                  /\\___/\\ \n";
        std::cout << "                 ( o   o ) \n";
        std::cout << "                 (  =^=  ) \n";
        std::cout << "                 (        ) \n";
        std::cout << "                 (         ) \n";
        std::cout << "                 (          )))))) \n\n";
    } else {
        std::cout << "        [ERROR] Test Failed. Check hardware or driver.\n\n";
    }

    close(fd);
    return 0;
}
