# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/HW4_system/HW4_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system || ORIG_REF_NAME==HW4_system} -quiet] -quiet

# IP: bd/HW4_system/ip/HW4_system_processing_system7_0_0/HW4_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system_processing_system7_0_0 || ORIG_REF_NAME==HW4_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/HW4_system/ip/HW4_system_HW4IP_0_0/HW4_system_HW4IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system_HW4IP_0_0 || ORIG_REF_NAME==HW4_system_HW4IP_0_0} -quiet] -quiet

# IP: bd/HW4_system/ip/HW4_system_ps7_0_axi_periph_0/HW4_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==HW4_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HW4_system/ip/HW4_system_rst_ps7_0_100M_0/HW4_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==HW4_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/HW4_system/ip/HW4_system_auto_pc_0/HW4_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW4_system_auto_pc_0 || ORIG_REF_NAME==HW4_system_auto_pc_0} -quiet] -quiet

# XDC: bd/HW4_system/HW4_system_ooc.xdc
