# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/Lab2_system_system_ila_0_0.xci
# IP: The module: 'Lab2_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/bd_2e5d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2e5d || ORIG_REF_NAME==bd_2e5d} -quiet] -quiet

# IP: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/bd_2e5d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/bd_2e5d_ila_lib_0_ooc.xdc

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/bd_2e5d_ooc.xdc

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/Lab2_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/Lab2_system_system_ila_0_0.xci
# IP: The module: 'Lab2_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/bd_2e5d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2e5d || ORIG_REF_NAME==bd_2e5d} -quiet] -quiet

# IP: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/bd_2e5d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2e5d_ila_lib_0 || ORIG_REF_NAME==bd_2e5d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/ip/ip_0/bd_2e5d_ila_lib_0_ooc.xdc

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/bd_0/bd_2e5d_ooc.xdc

# XDC: c:/Users/ryanh/Lab2_demo/Lab2_demo.srcs/sources_1/bd/Lab2_system/ip/Lab2_system_system_ila_0_0/Lab2_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
