# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab2_two_slaves/Lab2_two_slaves.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves || ORIG_REF_NAME==Lab2_two_slaves} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_Lab2_IP_0_0/Lab2_two_slaves_Lab2_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_Lab2_IP_0_0 || ORIG_REF_NAME==Lab2_two_slaves_Lab2_IP_0_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_Lab2_IP_1_0/Lab2_two_slaves_Lab2_IP_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_Lab2_IP_1_0 || ORIG_REF_NAME==Lab2_two_slaves_Lab2_IP_1_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_processing_system7_0_0/Lab2_two_slaves_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_processing_system7_0_0 || ORIG_REF_NAME==Lab2_two_slaves_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_xbar_0/Lab2_two_slaves_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_xbar_0 || ORIG_REF_NAME==Lab2_two_slaves_xbar_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_auto_pc_0/Lab2_two_slaves_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_auto_pc_0 || ORIG_REF_NAME==Lab2_two_slaves_auto_pc_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_ps7_0_axi_periph_0/Lab2_two_slaves_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab2_two_slaves_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab2_two_slaves/ip/Lab2_two_slaves_rst_ps7_0_100M_0/Lab2_two_slaves_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab2_two_slaves_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab2_two_slaves_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Lab2_two_slaves/Lab2_two_slaves_ooc.xdc
