# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryanh/Lab1_SDK/Lab1_SDK.srcs/sources_1/bd/Lab1_SDK_sys/ip/Lab1_SDK_sys_processing_system7_0_0/Lab1_SDK_sys_processing_system7_0_0.xci
# IP: The module: 'Lab1_SDK_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryanh/Lab1_SDK/Lab1_SDK.srcs/sources_1/bd/Lab1_SDK_sys/ip/Lab1_SDK_sys_processing_system7_0_0/Lab1_SDK_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab1_SDK_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ryanh/Lab1_SDK/Lab1_SDK.srcs/sources_1/bd/Lab1_SDK_sys/ip/Lab1_SDK_sys_processing_system7_0_0/Lab1_SDK_sys_processing_system7_0_0.xci
# IP: The module: 'Lab1_SDK_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryanh/Lab1_SDK/Lab1_SDK.srcs/sources_1/bd/Lab1_SDK_sys/ip/Lab1_SDK_sys_processing_system7_0_0/Lab1_SDK_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab1_SDK_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
